version: "3"
services:
  ws:
    build:
      context: ./filedrop-ws
      dockerfile: Dockerfile
    environment:
      - WS_HOST=0.0.0.0
      - WS_BEHIND_PROXY=yes
      - TURN_MODE=hmac
      - TURN_SERVER=turn:localhost
      - TURN_USERNAME=filedrop
      - TURN_SECRET=abcd

  web:
    build:
      context: ./filedrop-web
      dockerfile: Dockerfile
      args:
        - TITLE=filedrop
        - SERVER=ws://localhost/ws/

  coturn:
    image: instrumentisto/coturn
    command: --use-auth-secret --static-auth-secret=abcd --no-tls --no-dtls

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx:/etc/nginx
    command: /bin/sh -c "nginx -g \"daemon off;\""
